"""create_lists_and_game_lists_tables

Revision ID: 7f5e1dd0eb6c
Revises: 8e8ba41881de
Create Date: 2023-02-20 22:02:42.148613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5e1dd0eb6c'
down_revision = '8e8ba41881de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_lists',
    sa.Column('lists', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['games'], ['games.id'], ),
    sa.ForeignKeyConstraint(['lists'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('lists', 'games')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_lists')
    op.drop_table('lists')
    # ### end Alembic commands ###
